name: DevSecOps Pipeline

on:

  push:

  pull_request:

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: 20

      - run: npm install

      - run: npm test || true
      
      - name: Sonar Scan

        uses: SonarSource/sonarqube-scan-action@v5

        env:

          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
